import { useCallback, useEffect, useRef, useState, type CSSProperties } from 'react'
import { MusProvider, FeedbackTarget, onDemoFeedback, type DemoEvent, type FeedbackTargetHandle } from '@datachef/mus'
import '@datachef/mus/styles.css'
import {
  LayoutDashboard,
  BarChart3,
  MapPin,
  Settings,
  Bell,
  Sparkles,
  RotateCcw,
  ArrowRight,
  Hash,
  Lock,
  Headphones,
  Play,
} from 'lucide-react'

const SECTION_IDS = ['ai-summary', 'forecast', 'ranking', 'report-narrative', 'segments']

// The sample app's pages. Sidebar nav switches between them so the demo reads
// like a real product, not a single static screen. MUS rides on the AI/output
// pages (ai: true), never on chrome like Settings.
const VIEWS = [
  { id: 'insights', label: 'Insights', icon: LayoutDashboard, crumb: 'Insights', title: 'Q3 Business Review', ai: true },
  { id: 'reports', label: 'Reports', icon: BarChart3, crumb: 'Reports', title: 'Quarterly Report', ai: true },
  { id: 'segments', label: 'Segments', icon: MapPin, crumb: 'Segments', title: 'Audience Segments', ai: true },
  { id: 'settings', label: 'Settings', icon: Settings, crumb: 'Settings', title: 'Workspace Settings', ai: false },
] as const

type ViewId = (typeof VIEWS)[number]['id']

// ---- Mock Slack ("what your team sees") ----------------------------------
// The sandbox runs in demoMode, so nothing hits Slack. Instead we mirror the
// real server flow (src/server/index.ts): a thumbs/voice note posts into the
// shared #feedback channel, and a support request spins up a private
// per-user channel (support-<project>-<email>), invites the team, and pings
// #feedback. This panel visualises that so the payoff isn't just a toast.

const slugify = (s: string) =>
  s
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')

interface SlackMessage {
  id: number
  author: string
  avatar: string
  color: string
  body: string
  section?: string
  kind?: 'text' | 'voice' | 'reaction' | 'system'
}

interface SlackChannel {
  id: string
  name: string
  private?: boolean
}

const FEEDBACK_CHANNEL: SlackChannel = { id: 'feedback', name: 'pulse-ai-feedback' }

const SUPPORT_TEAM = [
  { name: 'Ava K.', avatar: 'AK', color: '#7c5cff' },
  { name: 'Milan R.', avatar: 'MR', color: '#0f9d8a' },
]

const initialMessages = (): Record<string, SlackMessage[]> => ({
  feedback: [
    {
      id: 0,
      author: 'MUS',
      avatar: '💡',
      color: '#2b2b3a',
      kind: 'system',
      body: 'This is where in-context feedback lands. Rate a card, leave a voice note, or open support in the sandbox to see it arrive here, with the exact section attached.',
    },
  ],
})

const prefersReducedMotion = () =>
  typeof window !== 'undefined' &&
  typeof window.matchMedia === 'function' &&
  window.matchMedia('(prefers-reduced-motion: reduce)').matches

// ---- Small "this content is being generated by AI" primitives -------------
// Not real inference (the site is static and nothing leaves the browser), but
// the streaming/count-up motion makes the sandbox read like a live AI product
// instead of a hardcoded mockup.

function CountUp({
  value,
  prefix = '',
  suffix = '',
  decimals = 0,
  duration = 900,
  className,
}: {
  value: number
  prefix?: string
  suffix?: string
  decimals?: number
  duration?: number
  className?: string
}) {
  const [display, setDisplay] = useState('0')

  useEffect(() => {
    if (prefersReducedMotion()) {
      setDisplay(value.toFixed(decimals))
      return
    }
    let raf = 0
    let startTs: number | null = null
    const tick = (ts: number) => {
      if (startTs === null) startTs = ts
      const p = Math.min(1, (ts - startTs) / duration)
      const eased = 1 - Math.pow(1 - p, 3)
      setDisplay((value * eased).toFixed(decimals))
      if (p < 1) raf = requestAnimationFrame(tick)
    }
    raf = requestAnimationFrame(tick)
    return () => cancelAnimationFrame(raf)
  }, [value, decimals, duration])

  return (
    <span className={className}>
      {prefix}
      {display}
      {suffix}
    </span>
  )
}

function Typewriter({
  text,
  speed = 16,
  delay = 0,
  className,
}: {
  text: string
  speed?: number
  delay?: number
  className?: string
}) {
  const [count, setCount] = useState(0)

  useEffect(() => {
    if (prefersReducedMotion()) {
      setCount(text.length)
      return
    }
    setCount(0)
    let interval = 0
    const startTimer = window.setTimeout(() => {
      let i = 0
      interval = window.setInterval(() => {
        i += 1
        setCount(i)
        if (i >= text.length) window.clearInterval(interval)
      }, speed)
    }, delay)
    return () => {
      window.clearTimeout(startTimer)
      window.clearInterval(interval)
    }
  }, [text, speed, delay])

  const done = count >= text.length
  return (
    <span className={className}>
      {text.slice(0, count)}
      {!done && <span className="tw-caret" aria-hidden="true" />}
    </span>
  )
}

function SlackRow({ m }: { m: SlackMessage }) {
  if (m.kind === 'system') {
    return (
      <div className="slack-msg is-system">
        <span className="slack-sys-icon" aria-hidden="true">{m.avatar}</span>
        <span>{m.body}</span>
      </div>
    )
  }
  return (
    <div className="slack-msg">
      <span className="slack-avatar" style={{ background: m.color }}>{m.avatar}</span>
      <div className="slack-msg-main">
        <span className="slack-msg-head">
          <strong className="slack-msg-username">{m.author}</strong>
          <span className="slack-msg-time">now</span>
          {m.section && <span className="slack-context">💡 {m.section}</span>}
        </span>
        {m.kind === 'voice' ? (
          <span className="slack-voice">
            <span className="slack-voice-play"><Play size={11} strokeWidth={2.6} /></span>
            <span className="slack-wave" aria-hidden="true">
              {Array.from({ length: 24 }).map((_, i) => (
                <span key={i} style={{ height: `${5 + ((i * 5) % 15)}px` }} />
              ))}
            </span>
            <span className="slack-voice-time">0:12</span>
          </span>
        ) : (
          <span className="slack-msg-body">{m.body}</span>
        )}
      </div>
    </div>
  )
}

function SkeletonGrid() {
  return (
    <div className="playground-grid-3" aria-hidden="true">
      {[0, 1, 2].map((i) => (
        <div key={i} className="playground-skel" style={{ '--d': `${i * 0.12}s` } as CSSProperties}>
          <span className="playground-skel-line w-40" />
          <span className="playground-skel-stat" />
          <span className="playground-skel-line w-90" />
          <span className="playground-skel-line w-70" />
        </div>
      ))}
    </div>
  )
}

// ---- Other sample-app pages (reached via the working sidebar) -------------
// Reports & Segments are AI/output pages, so they carry a real MUS trigger.
// Settings is app chrome, deliberately no MUS, to show where the layer belongs.

function ReportsView() {
  const bars = [
    { label: 'EU', value: 82 },
    { label: 'North America', value: 64 },
    { label: 'APAC', value: 48 },
    { label: 'LATAM', value: 27 },
  ]
  return (
    <FeedbackTarget
      sectionId="report-narrative"
      sectionName="Executive Report"
      videoUrl="/videos/report-narrative.mp4"
    >
      <div className="playground-widget playground-report-card">
        <div className="playground-widget-header">
          <span className="playground-tag">
            <Sparkles size={11} strokeWidth={2.5} />
            AI-generated
          </span>
          <span className="playground-widget-title">Executive summary, Q3</span>
        </div>
        <p className="playground-widget-caption playground-report-narrative">
          <Typewriter text="Revenue grew 17.4% QoQ, led by EU expansion and a record-low 2.1% churn. Momentum is strongest in enterprise, while SMB remains the primary risk heading into Q4." />
        </p>
        <div className="playground-bars">
          {bars.map((b) => (
            <div className="playground-bar-row" key={b.label}>
              <span className="playground-bar-label">{b.label}</span>
              <span className="playground-bar-track">
                <span className="playground-bar-fill" style={{ width: `${b.value}%` }} />
              </span>
              <span className="playground-bar-value">{b.value}%</span>
            </div>
          ))}
        </div>
      </div>
    </FeedbackTarget>
  )
}

function SegmentsView() {
  const rows = [
    { name: 'Berlin Mitte', score: 94 },
    { name: 'Kreuzberg', score: 92 },
    { name: 'Prenzlauer Berg', score: 87 },
    { name: 'Charlottenburg', score: 78 },
    { name: 'Neukölln', score: 71 },
  ]
  return (
    <FeedbackTarget
      sectionId="segments"
      sectionName="Audience Segments"
      videoUrl="/videos/segments.mp4"
    >
      <div className="playground-widget">
        <div className="playground-widget-header">
          <span className="playground-tag tag-blue">Ranked</span>
          <span className="playground-widget-title">Top segments by opportunity score</span>
        </div>
        <div className="playground-segments">
          {rows.map((r, i) => (
            <div className="playground-segment-row" key={r.name}>
              <span className="playground-segment-rank">{i + 1}</span>
              <span className="playground-segment-name">{r.name}</span>
              <span className="playground-bar-track">
                <span className="playground-bar-fill" style={{ width: `${r.score}%` }} />
              </span>
              <span className="playground-bar-value">{r.score}</span>
            </div>
          ))}
        </div>
      </div>
    </FeedbackTarget>
  )
}

function SettingsView() {
  return (
    <div className="playground-settings">
      <div className="playground-settings-row">
        <div className="playground-settings-label">
          <span>Workspace name</span>
          <small>Shown across the app</small>
        </div>
        <div className="playground-settings-input">Acme Inc</div>
      </div>
      <div className="playground-settings-row">
        <div className="playground-settings-label">
          <span>Timezone</span>
          <small>Used for report scheduling</small>
        </div>
        <div className="playground-settings-input">Europe / Berlin</div>
      </div>
      <div className="playground-settings-row">
        <div className="playground-settings-label">
          <span>Weekly digest</span>
          <small>Emailed every Monday at 9:00</small>
        </div>
        <span className="playground-settings-switch is-on" aria-hidden="true">
          <span />
        </span>
      </div>
      <p className="playground-settings-note">
        <Sparkles size={12} strokeWidth={2.4} />
        No 💡 here. MUS rides on output and AI sections, not on app chrome like settings.
      </p>
    </div>
  )
}

export default function PlaygroundDemo() {
  // 'intro'  → a short written explanation of MUS is showing.
  // 'live'   → the sandbox app is mounted.
  const [phase, setPhase] = useState<'intro' | 'live'>('intro')
  // 'running' shows the skeleton shimmer; 'done' mounts the real, animated cards.
  const [gen, setGen] = useState<'idle' | 'running' | 'done'>('idle')
  // Bumping this remounts the card grid: restarts the generate animation and
  // wipes each FeedbackTarget's internal state (open toolbar, active thumb).
  const [runKey, setRunKey] = useState(0)
  const [regenerating, setRegenerating] = useState(false)

  // The MUS layer on/off switch flips config.enabled so users watch the
  // indicators appear on an otherwise ordinary app.
  const [musLayer, setMusLayer] = useState(true)

  // Which sample-app page is showing (sidebar nav).
  const [view, setView] = useState<ViewId>('insights')

  // Mock-Slack state ("what your team sees").
  const [slackChannels, setSlackChannels] = useState<SlackChannel[]>([FEEDBACK_CHANNEL])
  const [activeChannel, setActiveChannel] = useState<string>('feedback')
  const [slackMsgs, setSlackMsgs] = useState<Record<string, SlackMessage[]>>(initialMessages)

  const summaryRef = useRef<FeedbackTargetHandle>(null)
  const forecastRef = useRef<FeedbackTargetHandle>(null)
  const rankingRef = useRef<FeedbackTargetHandle>(null)
  const timers = useRef<number[]>([])
  const slackId = useRef(1)

  const clearTimers = () => {
    timers.current.forEach((t) => window.clearTimeout(t))
    timers.current = []
  }

  const handlePlaygroundMouseLeave = () => {
    summaryRef.current?.reset()
    forecastRef.current?.reset()
    rankingRef.current?.reset()
  }

  const resetSlack = () => {
    slackId.current = 1
    setSlackChannels([FEEDBACK_CHANNEL])
    setActiveChannel('feedback')
    setSlackMsgs(initialMessages())
  }

  // Mirror a captured demo action into the mock-Slack panel.
  const pushSlack = useCallback((event: DemoEvent) => {
    const p = event.payload
    const section = String(p.sectionName ?? 'this section')
    const mk = (m: Omit<SlackMessage, 'id'>): SlackMessage => ({ id: slackId.current++, ...m })

    if (event.type === 'support') {
      const project = String(p.projectName ?? 'Pulse AI')
      const emailLocal = String(p.email ?? 'demo@datachef.co').split('@')[0]
      const chanId = `support-${slugify(project)}-${slugify(emailLocal)}`
      const author = String(p.name ?? 'Demo User')
      const topic = String(p.topic ?? '').trim() || 'Can someone take a look at this section?'

      const seed: SlackMessage[] = [
        mk({ author: 'Slack', avatar: '🔒', color: '#2b2b3a', kind: 'system',
          body: `You created this private channel and invited ${author}.` }),
        mk({ author: 'Slack', avatar: '👋', color: '#2b2b3a', kind: 'system',
          body: `${SUPPORT_TEAM.map((t) => t.name).join(' and ')} from the support team were added.` }),
      ]
      const userMsg = mk({ author, avatar: 'DU', color: '#3b6fe0', kind: 'text', body: topic, section })
      // Ping #feedback on every support submit, and always name the section so
      // the team can see what it was about without opening the private channel.
      const feedbackPing = mk({ author: 'MUS', avatar: '🎧', color: '#2b2b3a', kind: 'text', section,
        body: `${author} opened a support request. Private channel #${chanId} created.` })

      setSlackChannels((prev) =>
        prev.some((c) => c.id === chanId) ? prev : [...prev, { id: chanId, name: chanId, private: true }],
      )
      setSlackMsgs((prev) => {
        const existed = !!prev[chanId]
        const base = prev[chanId] ?? []
        return {
          ...prev,
          [chanId]: existed ? [...base, userMsg] : [...base, ...seed, userMsg],
          feedback: [...(prev.feedback ?? []), feedbackPing],
        }
      })
      setActiveChannel(chanId)
      return
    }

    let msg: SlackMessage | null = null
    if (event.type === 'voice') {
      msg = mk({ author: 'Demo User', avatar: 'DU', color: '#3b6fe0', kind: 'voice', section,
        body: 'Voice note · 0:12' })
    } else if (event.type === 'thumbs-up' || event.type === 'thumbs-down') {
      const up = event.type === 'thumbs-up'
      msg = mk({ author: 'Demo User', avatar: 'DU', color: '#3b6fe0', kind: 'reaction', section,
        body: up ? 'reacted 👍 this answer was helpful' : 'reacted 👎 this answer missed the mark' })
    }
    if (!msg) return // ignore 'video' and anything non-team-facing
    const posted = msg
    setActiveChannel('feedback')
    setSlackMsgs((prev) => ({ ...prev, feedback: [...(prev.feedback ?? []), posted] }))
  }, [])

  useEffect(() => onDemoFeedback(pushSlack), [pushSlack])

  useEffect(() => () => clearTimers(), [])

  // Run the "AI is generating this report" sequence: skeleton shimmer, then
  // mount the real animated cards.
  const runGeneration = () => {
    clearTimers()
    // Thumbs votes persist in localStorage by design; clear them so a fresh
    // generation truly starts blank.
    SECTION_IDS.forEach((id) => window.localStorage?.removeItem(`mus-thumbs-${id}`))
    resetSlack()
    setGen('running')
    setRunKey((k) => k + 1)

    const revealDelay = prefersReducedMotion() ? 200 : 1500
    timers.current.push(
      window.setTimeout(() => setGen('done'), revealDelay),
    )
  }

  const startSandbox = () => {
    setPhase('live')
    setView('insights')
    runGeneration()
  }

  const regenerate = () => {
    setRegenerating(true)
    setView('insights')
    runGeneration()
    window.setTimeout(() => setRegenerating(false), 700)
  }

  const changeView = (v: ViewId) => {
    if (v === view) return
    summaryRef.current?.reset()
    forecastRef.current?.reset()
    rankingRef.current?.reset()
    setView(v)
  }

  const activeChannelObj = slackChannels.find((c) => c.id === activeChannel)
  const activeView = VIEWS.find((v) => v.id === view) ?? VIEWS[0]

  return (
    <MusProvider
      config={{
        projectName: 'Pulse AI',
        demoMode: true,
        enabled: musLayer,
        showWelcomeDialog: false,
        theme: 'dark',
        hoverDelay: 300,
        slack: {
          proxyUrl: '',
          supportTeamEmails: ['demo@datachef.co'],
          feedbackChannelId: 'DEMO',
        },
        user: {
          name: 'Demo User',
          email: 'demo@datachef.co',
        },
        actions: [
          { type: 'support' },
          { type: 'thumbs-down' },
          { type: 'thumbs-up' },
          { type: 'voice' },
          { type: 'video' },
        ],
      }}
    >
      <div className="playground-container">
        <div className="playground-mobile-notice">
          <video
            className="playground-mobile-gif"
            src="/mus-demo.mp4"
            autoPlay
            muted
            loop
            playsInline
            preload="metadata"
            aria-label="MUS demo: hovering an AI-generated card reveals a feedback toolbar. The recording shows a thumbs-up reaction, a support message opening a Slack channel, and a voice note being recorded and submitted."
          >
            {/* GIF fallback for browsers that, for whatever reason, won't play the inline video */}
            <img
              className="playground-mobile-gif"
              src="/mus-demo.gif"
              alt="MUS demo: hovering an AI-generated card reveals a feedback toolbar with voice, thumbs, support and video actions"
              loading="lazy"
            />
          </video>
          <div className="playground-mobile-caption">
            <strong>Desktop only for hands-on use</strong>
            <p>Here's what it looks like in action. Open this page on a laptop to try it yourself.</p>
          </div>
        </div>

        <div className={`playground-stage${phase === 'live' ? ' is-live' : ''}`}>
          <div className="playground-wrapper" onMouseLeave={handlePlaygroundMouseLeave}>
            <div className="playground-header">
              <div className="playground-dot dot-red" />
              <div className="playground-dot dot-yellow" />
              <div className="playground-dot dot-green" />
              <span className="playground-url">pulse-ai.com / {view}</span>
            </div>

            {phase === 'intro' ? (
              /* ---- Intro: a short written explanation, then enter the sandbox ---- */
              <div className="sandbox-intro">
                <div className="sandbox-intro-copy">
                  <span className="sandbox-intro-eyebrow">
                    <Sparkles size={13} strokeWidth={2.4} />
                    What is MUS?
                  </span>
                  <h3 className="sandbox-intro-title">A feedback layer for your product, in context</h3>
                  <p className="sandbox-intro-text">
                    MUS drops a feedback trigger onto any section of your app. Users react with thumbs, a voice note, or
                    a support request right where they see the output, and it routes to your team in Slack with the full
                    context attached.
                  </p>
                  <p className="sandbox-intro-text">
                    Below is a live sandbox running the real widget on a sample app. Launch it, then{' '}
                    <strong>hover your cursor over any section to reveal its 💡 feedback trigger</strong> and react with a
                    rating, a voice note, or a support request. On the right you'll see exactly what your team receives.
                  </p>
                  <button type="button" className="sandbox-intro-cta" onClick={startSandbox}>
                    Launch the sandbox
                    <ArrowRight size={16} strokeWidth={2.4} />
                  </button>
                  <span className="sandbox-intro-note">Fully interactive. Nothing you do here leaves your browser.</span>
                </div>
              </div>
            ) : (
              /* ---- The live sandbox: a real AI insights app wrapped in MUS ---- */
              <div className="playground-appshell">
                <div className="playground-sidebar">
                  <div className="playground-sidebar-logo">
                    <span className="playground-sidebar-logo-mark">P</span>
                    <span className="playground-sidebar-logo-text">Pulse AI</span>
                  </div>
                  <nav className="playground-sidebar-nav">
                    {VIEWS.map((v) => {
                      const NavIcon = v.icon
                      return (
                        <button
                          type="button"
                          key={v.id}
                          className={`playground-sidebar-item${v.id === view ? ' is-active' : ''}`}
                          onClick={() => changeView(v.id)}
                          aria-current={v.id === view ? 'page' : undefined}
                        >
                          <NavIcon size={15} strokeWidth={2} />
                          {v.label}
                        </button>
                      )
                    })}
                  </nav>
                </div>

                <div className="playground-main">
                  <div className="playground-topbar">
                    <div className="playground-topbar-titles">
                      <span className="playground-topbar-crumb">{activeView.crumb}</span>
                      <span className="playground-topbar-title">{activeView.title}</span>
                    </div>
                    <div className="playground-topbar-right">
                      {/* {activeView.ai && (
                        <button
                          type="button"
                          role="switch"
                          aria-checked={musLayer}
                          className={`playground-layer-toggle${musLayer ? ' is-on' : ''}`}
                          onClick={() => setMusLayer((v) => !v)}
                          title={
                            musLayer
                              ? 'MUS layer is ON. Feedback indicators are live on every AI section'
                              : 'MUS layer is OFF. This is just the plain app'
                          }
                        >
                          <Sparkles size={12} strokeWidth={2.4} />
                          <span className="playground-layer-toggle-label">MUS layer</span>
                          <span className="playground-layer-switch">
                            <span className="playground-layer-knob" />
                          </span>
                        </button>
                      )} */}
                      {view === 'insights' && (
                        <button
                          type="button"
                          className="playground-regen"
                          onClick={regenerate}
                          disabled={gen === 'running'}
                        >
                          <RotateCcw size={13} strokeWidth={2.2} className={regenerating ? 'is-spinning' : undefined} />
                          Regenerate
                        </button>
                      )}
                      <span className="playground-bell">
                        <Bell size={16} strokeWidth={2} />
                        <span className="playground-bell-dot" />
                      </span>
                      <span className="playground-avatar">DU</span>
                    </div>
                  </div>

                  <div className="playground-body">
                    {/* {activeView.ai && (
                      <p
                        className={`playground-hint${
                          gen === 'running' && view === 'insights' ? ' is-generating' : ''
                        }`}
                      >
                        {gen === 'running' && view === 'insights' ? (
                          <>
                            <Sparkles size={13} strokeWidth={2.4} className="playground-hint-spark" />
                            Generating insights from Q3 data…
                          </>
                        ) : (
                          <>
                            <Sparkles size={12} strokeWidth={2.4} />
                            AI-generated · just now. The 💡 on each section is MUS. React, ask, or escalate.
                          </>
                        )}
                      </p>
                    )} */}

                    {view === 'insights' &&
                      (gen === 'running' ? (
                        <SkeletonGrid />
                      ) : (
                        <div className="playground-grid-3" key={runKey}>
                          {/* Card 1: AI executive summary */}
                          <FeedbackTarget
                            ref={summaryRef}
                            sectionId="ai-summary"
                            sectionName="AI Summary"
                            videoUrl="/videos/ai-summary.mp4"
                          >
                            <div className="playground-widget">
                              <div className="playground-widget-header">
                                <span className="playground-tag">
                                  <Sparkles size={11} strokeWidth={2.5} />
                                  AI-generated
                                </span>
                                <span className="playground-widget-title">Quarterly Performance</span>
                              </div>
                              <div className="playground-widget-hero">
                                <CountUp
                                  className="playground-widget-stat"
                                  value={17.4}
                                  prefix="+"
                                  suffix="%"
                                  decimals={1}
                                />
                                <span className="playground-widget-stat-label">Revenue, QoQ</span>
                              </div>
                              <p className="playground-widget-caption">
                                <Typewriter text="Revenue climbed on EU expansion while churn fell to 2.1%, the lowest in eight quarters." />
                              </p>
                            </div>
                          </FeedbackTarget>

                          {/* Card 2: Forecast */}
                          <FeedbackTarget
                            ref={forecastRef}
                            sectionId="forecast"
                            sectionName="Revenue Forecast"
                            videoUrl="/videos/forecast.mp4"
                          >
                            <div className="playground-widget">
                              <div className="playground-widget-header">
                                <span className="playground-tag">Forecast</span>
                                <span className="playground-widget-title">Next Quarter</span>
                              </div>
                              <div className="playground-widget-hero">
                                <CountUp
                                  className="playground-widget-stat"
                                  value={2.4}
                                  prefix="€"
                                  suffix="M"
                                  decimals={1}
                                />
                                <span className="playground-widget-stat-label">Expected revenue</span>
                              </div>
                              <p className="playground-widget-caption">
                                <Typewriter
                                  delay={250}
                                  text="87% confidence. Medium churn risk, concentrated in the SMB tier."
                                />
                              </p>
                            </div>
                          </FeedbackTarget>
                        </div>
                      ))}

                    {view === 'reports' && <ReportsView />}
                    {view === 'segments' && <SegmentsView />}
                    {view === 'settings' && <SettingsView />}

                    {gen === 'done' && view === 'insights' && (
                      <div className="playground-footer-actions">
                        <button type="button" className="playground-textbtn" onClick={() => setPhase('intro')}>
                          Read the intro again
                        </button>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Mock Slack, "what your team sees". In demoMode nothing hits Slack;
              this mirrors the real server flow so the payoff is visible. */}
          {phase === 'live' && (
            <div className="slack-window" aria-label="Mock Slack, what your team sees">
              <div className="slack-topbar">
                <div className="playground-dot dot-red" />
                <div className="playground-dot dot-yellow" />
                <div className="playground-dot dot-green" />
                <span className="slack-topbar-title">
                  <Headphones size={12} strokeWidth={2.2} />
                  Your team's Slack
                </span>
              </div>
              <div className="slack-body">
                <div className="slack-rail">
                  <span className="slack-rail-workspace">Acme Inc</span>
                  <span className="slack-rail-heading">Channels</span>
                  {slackChannels.map((c) => (
                    <button
                      key={c.id}
                      type="button"
                      className={`slack-rail-item${c.id === activeChannel ? ' is-active' : ''}`}
                      onClick={() => setActiveChannel(c.id)}
                    >
                      {c.private ? <Lock size={12} strokeWidth={2.2} /> : <Hash size={12} strokeWidth={2.2} />}
                      <span className="slack-rail-name">{c.name}</span>
                    </button>
                  ))}
                </div>
                <div className="slack-messages">
                  <div className="slack-channel-head">
                    {activeChannelObj?.private ? <Lock size={13} strokeWidth={2.2} /> : <Hash size={13} strokeWidth={2.2} />}
                    <span className="slack-channel-name">{activeChannelObj?.name}</span>
                    {activeChannelObj?.private && <span className="slack-private-badge">private</span>}
                  </div>
                  <div className="slack-scroll">
                    {(slackMsgs[activeChannel] ?? []).map((m) => (
                      <SlackRow key={m.id} m={m} />
                    ))}
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </MusProvider>
  )
}
